config/routes.rb
Rails.application.routes.draw do
  get 'images/new'

  get 'images/create'

  get 'pages/home' => 'high_voltage/pages#show', id: 'home'
  root to: 'pages#show', id: 'home'

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    get 'main', to: 'main#index', as: :authenticated_root
    resources :posts
    resources :images, only: [ :new, :create ]
    namespace :users do
      resources :relationships, only: %w(create destroy)
    end
  end
end

app/views/shared/_index_bar.html.haml
.index-bar-layout.layout
  %h2=title
  %ul.index-list
    - items.each do |item|
      = render partial: 'posts/post', locals: { post: item }

app/views/shared/_main.html.haml
.main-view.layout
  main view

app/views/shared/_nav.html.haml
.nav-bar-layout.p-2.layout.d-flex.flex-column.align-items-center.nav-background-full
  = link_to posts_path do
    = image_tag "logo-small.svg", class: "logo-small"
  = link_to authenticated_root_path do
    = image_tag "icon-map-dropper.svg", class:"icon-image-md"
    %div.d-flex.align-items-center
      .link-effects
        &nbsp;Map
  = link_to posts_path do
    = image_tag "posts.svg", class:"icon-image-sm"
    %div.d-flex.align-items-center
      .link-effects
        Posts
  = link_to new_image_path do
    = image_tag "icon-add.svg", class:"icon-image-sm"
    %div.d-flex.align-items-center
      .link-effects
        Add Post


  .avatar.mt-auto
    = link_to edit_user_registration_path do
      = image_tag current_user.gravatar_url, class: "avatar-round"
    = link_to 'Logout', destroy_user_session_path, method: :delete, class:"link-effects"